apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-cluster
  region: eu-west-2
  version: "1.27"
availabilityZones: ["eu-west-2a", "eu-west-2b"]
managedNodeGroups:
- name: mynodegroup
  desiredCapacity: 2
  instanceType: t2.medium
  ssh:
    enableSsm: true
  iam:
    withAddonPolicies:
      imageBuilder: true
      autoscaler: true
      externalDNS: true
      certManager: true
      ebs: true
      albIngress: true
      xRay: true
iam:
  withOIDC: true
# karpenter:
#   version: '0.29.2'
secretsEncryption:
  keyARN: ${MASTERARN}

